from basics.types import *

# SESSION_TOKEN = Text
# USERNAME = Text


# STATUTORY_ID = UInt8

# Test_Custom_level_integer = CustomIntegerType(0,100)
# Test_Custom_level_string = CustomTextType(100)
# Text50 = CustomTextType(50)
# normal_text = Text50

Text20 = CustomTextType(20)
Text50 = CustomTextType(50)
Text100 = CustomTextType(100)
Text250 = CustomTextType(250)
Text500 = CustomTextType(500)

SESSION_TOKEN = Text50
USERNAME = Text100
PASSWORD = Text20
URL = Text250
MENU_NAME = Text50
EMPLOYEE_CODE = Text50
USER_GROUP_NAME = Text50
EMAIL_ID = Text100
ADDRESS = Text250
FORM_NAME = Text50
MAPPING_NAME = Text500
DOCUMENT_NAME =  Text50
COMPLIANCE_NAME = Text50
FORMAT_FILE_NAME = Text50
GEOGRAPHY_MAPPING_NAME = Text500
UNIT_CODE = Text20
LEVEL_1_STATUTORY_NAME = Text50
CONTACT_NUMBER = Text20
UNIT_NAME = Text50
EMPLOYEE_NAME = Text50
COMPLIANCE_TASK_NAME = Text50
RESET_TOKEN = Text50
DATE = Text20
COUNTRY_NAME = Text50
DOMAIN_NAME = Text50
LEVEL_NAME = Text50
GEOGRAPHY_NAME = Text50
INDUSTRY_NAME = Text50
STATUTORY_NATURE_NAME = Text50
STATUTORY_NAME = Text50
STATUTORY_PROVISION = Text500
DESCRIPTION = Text500
CLIENT_NAME = Text50
BUSINESS_GROUP_NAME = Text50
LEGAL_ENTITY_NAME = Text50
DIVISION_NAME= Text50
SERVICE_PROVIDER_NAME= Text50
DESIGNATION = Text50
NOTIFICATION_TYPE = Text20
NOTIFICATION_TEXT = Text
STATUTORY_LEVEL1_NAME = Text50
FILTER_NAME = Text100
CONTACT_PERSON = Text50
NOTIFICATION_TYPE = Text20
STATUTORY_LEVEL1_NAME = Text50
FILTER_NAME = Text100
FORM_CATEGORY_NAME = Text50
FORM_TYPE_NAME = Text50
SHORT_NAME = Text20
LOCATION = Text250

LEVEL_ID = UInt8
STATUTORY_ID = UInt32
STATUTORY_MAPPING_ID = UInt32
GROUP_ID = UInt32
CLIENT_ID = UInt32
BUSINESS_GROUP_ID = UInt32
LEGAL_ENTITY_ID = UInt32
DIVISION_ID = UInt32
UNIT_ID = UInt32
COMPLIANCE_HISTORY_ID = UInt32
SERVICE_PROVIDER_ID = UInt32
CLIENT_USER_GROUP_ID = UInt32
COMPLIANCE_ID = UInt32
STATUTORY_NATURE_ID = UInt8
COUNTRY_ID = UInt8
DOMAIN_ID = UInt8
FORM_ID = UInt8
FORM_CATEGORY_ID = UInt8
INDUSTRY_ID = UInt8
USER_ID = UInt32
USER_GROUP_ID = UInt32
GEOGRAPHY_LEVEL_ID = UInt32
GEOGRAPHY_ID = UInt32
STATUTORY_LEVEL_ID = UInt32
LEVEL_1_STATUTORY_ID = UInt32
NO_OF_USER_LICENCE = UInt8
REMAINING_USER_LICENCE = UInt8
TOTAL_DISK_SPACE = Float
NOTIFICATION_ID = UInt32
USED_DISK_SPACE = UInt32
CLIENT_SAVED_STATUTORY_ID = UInt32
CLIENT_ASSIGNED_STATUTORY_ID = UInt32
NO_OF_COMPLIANCES = UInt8
AGEING = UInt8
NOTIFICATION_ID = UInt32
FILTER_ID = UInt32
FORM_TYPE_ID = UInt8
REPEATS_TYPE_ID = UInt8
DURATION_TYPE_ID = UInt8
FREQUENCY_ID = UInt8
APPROVAL_STATUS_ID = UInt8

STATUS	= Bool
IS_ACTIVE = Bool
HAS_READ = Bool


TIMESTAMP = Float

USER_LEVEL = CustomIntegerType(1,10)
LEVEL_POSITION = CustomIntegerType(1,10)
STATUTORY_DATE = CustomIntegerType(1, 31)
STATUTORY_MONTH = CustomIntegerType(1, 12)
REMINDER_DAYS = CustomIntegerType(1, 7)

